// Add these to your existing actionTypes.js file

// Auth Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";
export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE";

// User Actions
export const GET_USER_REQUESTS_REQUEST = "GET_USER_REQUESTS_REQUEST";
export const GET_USER_REQUESTS_SUCCESS = "GET_USER_REQUESTS_SUCCESS";
export const GET_USER_REQUESTS_FAILURE = "GET_USER_REQUESTS_FAILURE";
export const APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST";
export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS";
export const APPROVE_USER_FAILURE = "APPROVE_USER_FAILURE";
export const REJECT_USER_REQUEST = "REJECT_USER_REQUEST";
export const REJECT_USER_SUCCESS = "REJECT_USER_SUCCESS";
export const REJECT_USER_FAILURE = "REJECT_USER_FAILURE";
export const GET_USER_BY_SERVICE_NO_REQUEST = "GET_USER_BY_SERVICE_NO_REQUEST";
export const GET_USER_BY_SERVICE_NO_SUCCESS = "GET_USER_BY_SERVICE_NO_SUCCESS";
export const GET_USER_BY_SERVICE_NO_FAILURE = "GET_USER_BY_SERVICE_NO_FAILURE";

// Ship Actions
export const GET_SHIPS_REQUEST = "GET_SHIPS_REQUEST";
export const GET_SHIPS_SUCCESS = "GET_SHIPS_SUCCESS";
export const GET_SHIPS_FAILURE = "GET_SHIPS_FAILURE";
export const SET_SELECTED_SHIP_JMAIN = "SET_SELECTED_SHIP_JMAIN";
export const GET_SHIP_DETAILS_REQUEST = "GET_SHIP_DETAILS_REQUEST";
export const GET_SHIP_DETAILS_SUCCESS = "GET_SHIP_DETAILS_SUCCESS";
export const GET_SHIP_DETAILS_FAILURE = "GET_SHIP_DETAILS_FAILURE";
export const ADD_SHIP_REQUEST = "ADD_SHIP_REQUEST";
export const ADD_SHIP_SUCCESS = "ADD_SHIP_SUCCESS";
export const ADD_SHIP_FAILURE = "ADD_SHIP_FAILURE";
export const UPDATE_SHIP_REQUEST = "UPDATE_SHIP_REQUEST";
export const UPDATE_SHIP_SUCCESS = "UPDATE_SHIP_SUCCESS";
export const UPDATE_SHIP_FAILURE = "UPDATE_SHIP_FAILURE";
export const FETCH_SHIPS_REQUEST = "FETCH_SHIPS_REQUEST";
export const FETCH_SHIPS_SUCCESS = "FETCH_SHIPS_SUCCESS";
export const FETCH_SHIPS_FAILURE = "FETCH_SHIPS_FAILURE";

// Project Actions
export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
export const GET_PROJECT_DETAILS_REQUEST = "GET_PROJECT_DETAILS_REQUEST";
export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS";
export const GET_PROJECT_DETAILS_FAILURE = "GET_PROJECT_DETAILS_FAILURE";
export const UPDATE_PROJECT_PROGRESS_REQUEST =
  "UPDATE_PROJECT_PROGRESS_REQUEST";
export const UPDATE_PROJECT_PROGRESS_SUCCESS =
  "UPDATE_PROJECT_PROGRESS_SUCCESS";
export const UPDATE_PROJECT_PROGRESS_FAILURE =
  "UPDATE_PROJECT_PROGRESS_FAILURE";

// Theme Actions
export const TOGGLE_THEME = "TOGGLE_THEME";
export const SET_THEME = "SET_THEME";

// UI Actions
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const CLEAR_AUTH_ERRORS = "CLEAR_AUTH_ERRORS";
