// Feedback Actions
export const GET_FEEDBACK_DATES_REQUEST = "GET_FEEDBACK_DATES_REQUEST";
export const GET_FEEDBACK_DATES_SUCCESS = "GET_FEEDBACK_DATES_SUCCESS";
export const GET_FEEDBACK_DATES_FAILURE = "GET_FEEDBACK_DATES_FAILURE";

export const GET_JMAIN_REQUEST = "GET_JMAIN_REQUEST";
export const GET_JMAIN_SUCCESS = "GET_JMAIN_SUCCESS";
export const GET_JMAIN_FAILURE = "GET_JMAIN_FAILURE";

export const SUBMIT_FEEDBACK_REQUEST = "SUBMIT_FEEDBACK_REQUEST";
export const SUBMIT_FEEDBACK_SUCCESS = "SUBMIT_FEEDBACK_SUCCESS";
export const SUBMIT_FEEDBACK_FAILURE = "SUBMIT_FEEDBACK_FAILURE";

export const CLEAR_FEEDBACK_ERROR = "CLEAR_FEEDBACK_ERROR";
