// Project Actions
export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
export const GET_PROJECT_DETAILS_REQUEST = "GET_PROJECT_DETAILS_REQUEST";
export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS";
export const GET_PROJECT_DETAILS_FAILURE = "GET_PROJECT_DETAILS_FAILURE";
export const UPDATE_PROJECT_PROGRESS_REQUEST =
  "UPDATE_PROJECT_PROGRESS_REQUEST";
export const UPDATE_PROJECT_PROGRESS_SUCCESS =
  "UPDATE_PROJECT_PROGRESS_SUCCESS";
export const UPDATE_PROJECT_PROGRESS_FAILURE =
  "UPDATE_PROJECT_PROGRESS_FAILURE";
