// User Actions
export const GET_USER_REQUESTS_REQUEST = "GET_USER_REQUESTS_REQUEST";
export const GET_USER_REQUESTS_SUCCESS = "GET_USER_REQUESTS_SUCCESS";
export const GET_USER_REQUESTS_FAILURE = "GET_USER_REQUESTS_FAILURE";
export const APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST";
export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS";
export const APPROVE_USER_FAILURE = "APPROVE_USER_FAILURE";
export const REJECT_USER_REQUEST = "REJECT_USER_REQUEST";
export const REJECT_USER_SUCCESS = "REJECT_USER_SUCCESS";
export const REJECT_USER_FAILURE = "REJECT_USER_FAILURE";
export const GET_USER_BY_SERVICE_NO_REQUEST = "GET_USER_BY_SERVICE_NO_REQUEST";
export const GET_USER_BY_SERVICE_NO_SUCCESS = "GET_USER_BY_SERVICE_NO_SUCCESS";
export const GET_USER_BY_SERVICE_NO_FAILURE = "GET_USER_BY_SERVICE_NO_FAILURE";
